import uuid
from extensions import db
from models.base import BaseModel


class Intelligence(BaseModel):
    """
    Stores structured AI-generated intelligence for a piece of news or research.
    Designed to be provider-agnostic: the same schema works whether the analysis
    was generated by LocalIntelligenceProvider, Gemini, Claude, or any future
    provider. The 'provider' field records which engine produced the record.
    """
    __tablename__ = 'intelligence'

    id = db.Column(db.String(36), primary_key=True, default=lambda: str(uuid.uuid4()))

    # Polymorphic target reference — 'news' | 'research'
    content_type = db.Column(db.String(20), nullable=False, index=True)
    content_id   = db.Column(db.String(36), nullable=False, index=True)

    # Core intelligence output
    summary          = db.Column(db.Text, nullable=True)
    topics           = db.Column(db.JSON, nullable=True)   # list[str]
    entities         = db.Column(db.JSON, nullable=True)   # list[str]
    confidence_score = db.Column(db.Float, default=0.0, nullable=False)

    # Audit — which provider produced this record
    provider = db.Column(db.String(100), default='local', nullable=False)

    # Composite index: guarantees one intelligence record per content item
    __table_args__ = (
        db.Index('ix_intelligence_type_id', 'content_type', 'content_id', unique=True),
    )
