from extensions import db
from models.base import BaseModel

class StrategicSignal(BaseModel):
    """
    Represents a strategic intelligence signal generated by the platform.
    Categories include Opportunity, Risk, Emerging Trend, and Competitive Activity.
    """
    __tablename__ = 'strategic_signal'

    id = db.Column(db.Integer, primary_key=True)
    signal_type = db.Column(db.String(50), nullable=False, index=True)
    title = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text, nullable=False)
    confidence_score = db.Column(db.Float, default=0.0)

    def to_dict(self):
        """Serialize the signal to a dictionary."""
        return {
            'id': self.id,
            'signal_type': self.signal_type,
            'title': self.title,
            'description': self.description,
            'confidence_score': self.confidence_score,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None
        }

    def __repr__(self):
        return f"<StrategicSignal {self.signal_type}: {self.title}>"
